### ISSUE TITLE
Linux 用户无法直接使用 Times New Roman 和华文细黑（STXihei）字体

### ISSUE THREAD

**Issue by felinae98** [spencerwooo/BIThesis#15]
别问，archlinux折腾一上午了

**Comment by spencerwooo** [comment]
**经过和 @felinae98 的一番折腾，Linux 用户最方便的办法应该就是将 Windows 上的字体直接复制到 Linux 上面进行单独安装。**

Arch Linux 用户可以考虑使用 AUR 中提供的 [ttf-ms-fonts](https://aur.archlinux.org/packages/ttf-ms-fonts/) 安装 Times New Roman，但 STXihei 还是需要手动进行搜索、下载并进行安装。考虑到只有封面引用了 STXihei，如果实在无法解决，请直接用 Word 版模板导出封面 PDF 文件插入 LaTeX 之中，并将模板中使用 STXihei 的部分全部删除，这样的效果是一致的。
