### ISSUE TITLE
VS Code 配置编译命令时无法正确解析 JSON 格式的设置文件

### ISSUE THREAD

**Issue by sdrzwpx** [spencerwooo/BIThesis#17]
{
 "owner": "_generated_diagnostic_collection_name_#0",
 "severity": 8,
 "message": "End of file expected.",
 "source": "jsonc",
 "startLineNumber": 1,
 "startColumn": 29,
 "endLineNumber": 1,
 "endColumn": 30
}

**Comment by spencerwooo** [comment]
请提供一下详细的问题复现方法，包括：

- 你的 LaTeX 版本，`latexmk` 或 `xelatex` 版本
- 你的 VS Code 配置的编译命令（JSON 配置文件里面的内容）
- 编译失败的具体报错信息

谢谢。我个人并没有太看懂你上面提出的问题以及到底那里报出的错误。

**Comment by spencerwooo** [comment]
> 本问题已经通过邮件和原提问的同学进行了沟通并顺利解决了相应的问题，这里给出整个问题的基本复盘。

## 问题所在

提问的同学由于初次下载使用 VS Code，**其配置文件是完全空白的**，同学直接将教程中的部分编译命令代码粘贴进入 JSON 文件，导致 VS Code 报出语法错误（也就是开头的错误）：

```jsonc
{
	// setting 所在文件路径
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "End of file expected.",
	"source": "jsonc",
	"startLineNumber": 1,
	"startColumn": 29,
	"endLineNumber": 1,
	"endColumn": 30
}
```

这里的问题不是 LaTeX 本身的问题，而是 VS Code 无法正确解析对应的配置，导致报错。

## 解决方法

你的 VS Code 的设置文件实际上是一个 JSON 格式的纯文本文件，其中不仅包括了 LaTeX Workshop 的配置，还包括了其他 VS Code 的配置，比如字体、配色、行间距等等。你应该按照这样的语法对**新建的 VS Code 设置文件**进行配置：

```jsonc
{
  // ...
  "latex-workshop.latex.tools": [
    {
      "name": "latexmk",
      // ...
    }
  ],
  "latex-workshop.latex.recipes": [
    {
      "name": "latexmk 🔃",
      // ...
    }
  ],
  // ...
}
```

注意这里的整个配置文件是由一对 `{}` 包裹而成的，其中里面定义的是相应的编译配置。

另外，多个编译 `tools` 和 `recipes` 是可以并联（并列连接）的，在 JSON 中 `[]` 表示一个列表，因此比如我们想要将 `latexmk` 和 `xelatex` 一起加入 `"latex-workshop.latex.tools"`，即可这样设置：

```jsonc
{
  // ...
  "latex-workshop.latex.tools": [
    {
      "name": "latexmk",
      // ...
    },
    {
      "name": "xelatex",
      // ...
    }
  ],
}
```

对 `"latex-workshop.latex.recipes"` 的设置同理。希望可以帮到遇到类似问题的同学。
