### ISSUE TITLE
毕业论文模板中生成目录链接有误

### ISSUE THREAD

**Issue by Lylist** [spencerwooo/BIThesis#18]
目录中结论、参考文献页码和链接有误

**Comment by spencerwooo** [comment]
感谢！刚刚发现这个问题，经过一番研究，找到了一个比较方便的解决方法：

## 问题陈述

在毕业设计论文 LaTeX 模板中，正文之后的章节（包括结论、参考文献、附录和致谢）的页码和链接都出现了一个数字的偏差。

导致这个问题的原因主要是「LaTeX 无编号章节」需要手动声明，LaTeX 才会自动将这些章节加入 TOC 之中。也就是下面 `\addcontentsline{toc} ...` 的作用：

```latex
% 定义一个无编号章节
\chapter*{...}

% 将对应章节加入 TOC 自动生成
\addcontentsline{toc}{chapter}{...}
```

问题的主要是由于 `\addcontentsline` 和 `\chapter` 两个宏包的声明调用位置，原模板是先调用 `\addcontentsline` 再调用 `\chapter`，这里就导致了所有手动添加的章节页码都少了 1，所以解决方案也非常简单……

## 解决方案

将以下四个文件：

- `misc/3_conclusion.tex`
- `misc/4_reference.tex`
- `misc/5_appendix.tex`
- `misc/6_acknowledgements.tex`

里面的有效内容部分（即非注释部分）的第一行 `\addcontentsline{toc}{chapter} ...` 和第二行 `\chapter*{ ... }` 进行交换。比如结论文件 `misc/3_conclusion.tex`，按照下面的方法进行修改（红色表示删除，绿色表示新增）：

```diff
- \addcontentsline{toc}{chapter}{结~~~~论}
- \chapter*{\vskip 10bp\textmd{结~~~~论} \vskip -6bp}
+ \chapter*{\vskip 10bp\textmd{结~~~~论} \vskip -6bp}
+ \addcontentsline{toc}{chapter}{结~~~~论}
```

再次编译，重新索引目录，即可解决问题。

**我尽快发布更新，解决这一问题。再次感谢！**

**Comment by spencerwooo** [comment]
@Lylist 最新发布的版本应该解决这一问题了，请确认一下，谢谢~
