### ISSUE TITLE
毕业论文 LaTeX 模板生成目录点击摘要会直接跳到题目一页

### ISSUE THREAD

**Issue by playedcreat** [spencerwooo/BIThesis#24]
毕业论文点目录里的摘要会直接跳到题目那一页

**Comment by Lancern** [comment]
应用 https://github.com/spencerwooo/BIThesis/pull/25/files 中所示的修改应该就可以修复该问题。

**Comment by spencerwooo** [comment]
@playedcreat 应该已经解决了，可以用 master 分支的模板测试一下。

**Comment by playedcreat** [comment]
已解决，感谢
