### ISSUE TITLE
Unwanted blank page at the very end of the document

### ISSUE THREAD

**Issue by Lancern** [spencerwooo/BIThesis#27]
This is a rather minor problem. An unwanted blank page is inserted at the very end of the document:

<img width="450" alt="图片" src="https://user-images.githubusercontent.com/29401356/81821145-1b915900-9564-11ea-8a79-eabb51fd8dea.png">

This page should be removed.

**Comment by spencerwooo** [comment]
Weird, I don't see this blank page if I compile on Windows, but the Overleaf version does have this blank page. Any change it's OS specific?

**Comment by Lancern** [comment]
OS information:

```
$ uname -a
Darwin Lancern-MacbookPro 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
```

**Comment by Lancern** [comment]
Actually, my working thesis on Overleaf still has this problem.

**Comment by spencerwooo** [comment]
I can't reproduce this on Windows ψ(._. )> Does using MacTeX yield this issue too? People say TeX Live on macOS is poorly supported.

**Comment by Lancern** [comment]
My Tex Live is installed via MacTex using HomeBrew:

```
brew cask install mactex
```

And my working thesis on overleaf has this problem, too:

<img width="1438" alt="图片" src="https://user-images.githubusercontent.com/29401356/81824837-7dec5880-9568-11ea-8c78-d15f31625004.png">

On overleaf, I'm using Tex Live 2019 as my compiler.

**Comment by Lancern** [comment]
@spencerwooo Could you share your build log? It's typically in `main.log`. Maybe we can find something by comparing your build log with mine.

**Comment by spencerwooo** [comment]
Of course, have a look: https://pastebin.com/phLzgekA

**Comment by spencerwooo** [comment]
@Lancern Seems to be fixed with PR #30, I tested Windows/Linux and Overleaf, all are fixed. Can you confirm on macOS?

**Comment by Lancern** [comment]
Problem confirm **SOLVED** on macOS.

**Comment by Lancern** [comment]
Why could changing `\vspace` in abstract solve this problem?

**Comment by spencerwooo** [comment]
Actually removing `\topskip=0pt` solved the issue. Don't know why I used this in the first place...

**Comment by Lancern** [comment]
I've found a post that could explain why setting `\topskip` to 0 will result in an extra blank page: https://tex.stackexchange.com/a/334188

**Comment by Lancern** [comment]
I suggest reopen the issue:

<img width="479" alt="图片" src="https://user-images.githubusercontent.com/29401356/82894687-8e97c800-9f85-11ea-939e-305c0ba568b9.png">

**Comment by spencerwooo** [comment]
Is this before or after PR #44?

**Comment by Lancern** [comment]
Before.

**Comment by spencerwooo** [comment]
Can't reproduce...

**Comment by spencerwooo** [comment]
I'm using the newest template on Overleaf. (Updated after PR #30)

**Comment by Lancern** [comment]
I'll try to produce a MWE. My template on Overleaf does not sync with this project.

**Comment by Lancern** [comment]
My fault. I did not remove all `\topskip=0pt`.
