### ISSUE TITLE
About bib

### ISSUE THREAD

**Issue by SunriseBruce** [spencerwooo/BIThesis#29]
![捕获](https://user-images.githubusercontent.com/64565890/82040664-86b06c00-96d9-11ea-8ad3-95798832f287.PNG)
 I write the reference like what the video shows,but when I run my tex,it shows me this,and the there is no reference in my paper.So really need you help! Thank you
![1](https://user-images.githubusercontent.com/64565890/82040978-050d0e00-96da-11ea-8d48-f8399acfaa66.PNG)
![2](https://user-images.githubusercontent.com/64565890/82040987-0807fe80-96da-11ea-931e-6f4f21b5a482.PNG)

**Comment by spencerwooo** [comment]
应该是没有制定参考文献编译器，TeXstudio 设置一下参考文献编译用 biber 试试？具体见：https://bithesis.spencerwoo.com/Guide/2-Usage/Downloading-and-using-templates.html#使用-texstudio-撰写与编译-latex-模板

**Comment by SunriseBruce** [comment]
谢谢
