### ISSUE TITLE
写英文论文图标格式问题

### ISSUE THREAD

**Issue by chengxuxin** [spencerwooo/BIThesis#31]
现在的caption格式是“图 1-1”这样，我想改成“Fig. 1-1”这样。我试了`\renewcommand{\figurename}{Fig.}`是work的 但不太懂source code里面这句`\renewcommand{\thefigure}{\thechapter-\arabic{figure}}`

**Comment by spencerwooo** [comment]
Figure caption 的「图」是文档类型 `ctexbook` 定义的，你说的那行定义的是后面「1-1」的数字，所以你这里通过修改 `\figname` 是没有问题的。

**Comment by Lancern** [comment]
`\thefigure`是图片的编号。`\thechapter`是当前章节的编号或标题，`\arabic{figure}`是将`figure`计数器的值按照阿拉伯数字的格式显示出来。`\thefigure`将会被LaTeX展开为章节号-图片编号的形式，也就是说`\thefigure`形成图片的编号。`\figurename`是图片编号之前的前缀，默认是`图片`，也可以自定义成为`Fig.`。

**Comment by chengxuxin** [comment]
saoga，向大佬们学习了，gayhub真是个好地方
