### ISSUE TITLE
Poll / 意见征集：关于如何订阅本项目 Release 更新的投票

### ISSUE THREAD

**Issue by spencerwooo** [spencerwooo/BIThesis#32]
[![](https://api.gh-polls.com/poll/01E8HCA05KHNSY6VXM48QSSJN7/%F0%9F%93%A7%20GitHub%20release%20%E9%82%AE%E4%BB%B6%E9%80%9A%E7%9F%A5)](https://api.gh-polls.com/poll/01E8HCA05KHNSY6VXM48QSSJN7/%F0%9F%93%A7%20GitHub%20release%20%E9%82%AE%E4%BB%B6%E9%80%9A%E7%9F%A5/vote)
[![](https://api.gh-polls.com/poll/01E8HCA05KHNSY6VXM48QSSJN7/%F0%9F%9A%80%20Telegram%20%E7%BE%A4%E7%BB%84%E6%88%96%E9%A2%91%E9%81%93%E8%AE%A2%E9%98%85%20bot%20%E9%80%9A%E7%9F%A5)](https://api.gh-polls.com/poll/01E8HCA05KHNSY6VXM48QSSJN7/%F0%9F%9A%80%20Telegram%20%E7%BE%A4%E7%BB%84%E6%88%96%E9%A2%91%E9%81%93%E8%AE%A2%E9%98%85%20bot%20%E9%80%9A%E7%9F%A5/vote)
[![](https://api.gh-polls.com/poll/01E8HCA05KHNSY6VXM48QSSJN7/%F0%9F%92%AC%20Slack%20%E8%AE%BE%E7%BD%AE%E5%85%B3%E8%81%94%20GitHub%20%E7%9A%84%20Integration%20%E8%BF%9B%E8%A1%8C%E9%80%9A%E7%9F%A5)](https://api.gh-polls.com/poll/01E8HCA05KHNSY6VXM48QSSJN7/%F0%9F%92%AC%20Slack%20%E8%AE%BE%E7%BD%AE%E5%85%B3%E8%81%94%20GitHub%20%E7%9A%84%20Integration%20%E8%BF%9B%E8%A1%8C%E9%80%9A%E7%9F%A5/vote)

- 第一种（GitHub watch）是目前本项目的默认订阅方式，也是目前采用的发布订阅方式，但无法进行讨论
- 第二种（Telegram）更为直观（但也比较混乱）的一种方式，还可以建立讨论组方便各位进行交流学习（当然缺点就是需要科学上网）
- 第三种（Slack）是更为专业的协作软件，可以支持 thread 形式的对话，方便沉淀，同时也支持和 GitHub 进行链接（且不需要科学上网，但免费版可能有一些限制）

欢迎大家投票，如果后面几种更受欢迎，我会考虑设置本项目相关的 Telegram/Slack 讨论组。**本意见征集将持续 3 天至 5 月 20 日。**

> 为了添加新的 Slack 选项，前面的两个记录失效了……之前的 GitHub 和 Telegram 两个选项记录均为 4 票。

**Comment by Lancern** [comment]
有考虑过使用 slack 吗，不需要科学上网

**Comment by spencerwooo** [comment]
> 有考虑过使用 slack 吗，不需要科学上网

Slack 太贵了，1000 条 message 以上就要花钱了。不过类似的 Discord 其实也可以考虑。

**Comment by spencerwooo** [comment]
Okay，貌似免费版 Slack 也只是……1w 条可搜索的历史比较坑，感觉可以考虑 Slack？@Lancern

**Comment by spencerwooo** [comment]
感觉没人投票了，Slack 已经领先，要不就合了那个分支直接用 Slack 吧
