### ISSUE TITLE
使用 \autoref 自动显示引用名称应为中文

### ISSUE THREAD

**Issue by felinae98** [spencerwooo/BIThesis#38]
目前`\autoref{sec:2}`后显示结果是`chapter. 2`，预期结果应为`第2章`

**Comment by spencerwooo** [comment]
还有这种操作，我一直都直接 `\ref{}` 然后前后加上 `第` 和 `章`……是我孤陋寡闻了

**Comment by felinae98** [comment]
如果不能解决还是要像你这样来

**Comment by spencerwooo** [comment]
![image](https://user-images.githubusercontent.com/32114380/82354205-1421f200-9a33-11ea-870b-5ec1d5cd9340.png)

@felinae98 试一下 `\renewcommand{\sectionautorefname}{章节}`？

这样改的话，应该对：

- `\chapterautorefname`
- `\sectionautorefname`
- `\figureautorefname`
- `\tableautorefname`

都进行汉化修改。（不知道全不全，大概这些。）不过还是无法实现「第 x 章」，只能「章节 x」。因为英文对应的是 `section x`。

**Comment by felinae98** [comment]
参考http://static.latexstudio.net/wp-content/uploads/2018/03/swjtuthesis.pdf

**Comment by spencerwooo** [comment]
@felinae98 gkd!

**Comment by StudyingFather** [comment]
目前对于章节的引用似乎还是只有英文？表格和图片的 `\autoref` 倒是已经本地化了。

**Comment by YDX-2147483647** [comment]
> 目前对于章节的引用似乎还是只有英文？表格和图片的 `\autoref` 倒是已经本地化了。

https://bithesis.bitnp.net/faq/autoref-name.html

@StudyingFather “第1章”在数字后也有字，而 autoref 本来只支持“章 1”，需要 hack，就没有加进模板。

本来用 cleveref 最好（#596），但不兼容 TeX Live 2025，只能暂缓。
