### ISSUE TITLE
生僻字不能正常显示

### ISSUE THREAD

**Issue by Lancern** [spencerwooo/BIThesis#40]
这应该是上游的问题。某些生僻字，例如`燚`字，不能在编译出的pdf中正常显示。

<img width="1083" alt="图片" src="https://user-images.githubusercontent.com/29401356/82719922-46f11200-9ce1-11ea-88a0-68005edfc1b5.png">

**Comment by spencerwooo** [comment]
Windows 无法复现……

![image](https://user-images.githubusercontent.com/32114380/82720712-b6b6cb00-9ce8-11ea-9ab5-c738cbc20459.png)

**Comment by Lancern** [comment]
应该是字体的原因吧？字体库里面没有这个字

**Comment by felinae98** [comment]
archlinux可以复现

**Comment by Lancern** [comment]
macOS 可以复现，overleaf 可以复现

**Comment by spencerwooo** [comment]
参考国科大 ucasthesis 的解决方法：[Linux/Overleaf 系统的字体配置](https://github.com/mohuangrui/ucasthesis/wiki/%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE#linuxoverleaf-%E7%B3%BB%E7%BB%9F%E7%9A%84%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE)，macOS 的解决方法应该也类似。

**Comment by spencerwooo** [comment]
@Lancern Any progress?

**Comment by Lancern** [comment]
Not tested yet. I'll test it tomorrow.（咕咕咕
