### ISSUE TITLE
换页引起的图片位置错误

### ISSUE THREAD

**Issue by fky2015** [spencerwooo/BIThesis#41]
## 如何复现问题？

在 `1-chapter1.tex` 中插入两段 lorem，让图片卡在换行处即可触发。

![image](https://user-images.githubusercontent.com/16451516/82722335-6cd5e100-9cf8-11ea-9190-f6d3658c56ee.png)

*箭头所指为位置错误的图片和原本应该在的地方*

**Comment by spencerwooo** [comment]
正常现象啊？因为上一页图片放不下了啊

**Comment by fky2015** [comment]
然后接下来两张图片就充斥了整个页面：
![image](https://user-images.githubusercontent.com/16451516/82722432-406e9480-9cf9-11ea-85f0-6abddcea069a.png)

**Comment by fky2015** [comment]
而其实这样才是正常的排版：

![image](https://user-images.githubusercontent.com/16451516/82722457-87f52080-9cf9-11ea-8224-204969dbffb7.png)

**Comment by spencerwooo** [comment]
也正常呀，因为下面没有文本了，LaTeX 处理图片、表格、公式或者别的类似环境的换行就是这样子的，是那个 `htbp` 控制的，你可以给改成 `H`，强制图像留在原地。

**Comment by spencerwooo** [comment]
看这里：[Positioning images and tables](https://www.overleaf.com/learn/latex/positioning_images_and_tables)

![image](https://user-images.githubusercontent.com/32114380/82722488-d1457000-9cf9-11ea-8db5-f88fccf117f5.png)

**Comment by fky2015** [comment]
行吧，我意思就是直接换成 H，其他的感觉相对没有太多用。

**Comment by fky2015** [comment]
同时需要引入 float package

**Comment by spencerwooo** [comment]
Closed, see #42.
