### ISSUE TITLE
用TexStudio-xelatex编译报错，感谢作者的辛勤劳动~

### ISSUE THREAD

**Issue by sdrzwpx** [spencerwooo/BIThesis#5]
biblatex.sty   错误    行 10291: Package biblatex Error: Style 'gb7714-2015' not found. \RequireBibliographyStyle{\blx@bbxfile}
biblatex.sty   错误    行 10292: Package biblatex Error: Style 'gb7714-2015' not found. \RequireCitationStyle{\blx@cbxfile}
main.tex   错误    行 82: Undefined control sequence. \ctexset
main.tex   错误    行 82: Missing \begin{document}. \ctexset{s
main.tex   错误    行 91: Undefined control sequence. \ctexset
main.tex   错误    行 129: Package biblatex Error: Command '\cite' undefined. ...��毕业设计选题的主要内容 \cite

**Comment by spencerwooo** [comment]
请问确认是用 biber 编译的参考文献吗？我测试 Windows 和 macOS 命令行编译都没有问题，Overleaf 在线编译也没有问题。参考文献的后端编译器是 biber 不是 bibtex，很有可能是这个问题。

**Comment by spencerwooo** [comment]
还有请确认一下 TeX Live 的版本需要更新至 2019 版，旧版（2018 版）都会出问题，因为没有相应的参考文献格式文件，这个也请确认一下。
