### ISSUE TITLE
MikTeX 使用 biber 编译参考文献时 \cite 标签无法解析

### ISSUE THREAD

**Issue by Pengxiang-Li** [spencerwooo/BIThesis#50]
您好，我在使用BIThesis的graduation-thesis时，是使用Testudio+miktex编写的。在使用的过程中我已经将biber配置到configure的build中。
但是我在编写的过程中发现了这样的问题，使用\cite{某title}后，对应处没有出现引用超链接，而是把我\cite{}里的内容黑体加粗显示了。此外，引用过的文献也并没有在参考文献内显示。
报错为“Citation 'simonyanVeryDeepConvolutional2015' on page 35 undefined”
“Package biblatex Error: Incompatible package 'cite'. \blx@packageincompatibility”
奇怪的是我已经在bib文件中添加了这个文献了（这个文献引用是示例中给的），却仍然发生了这样的错误。
请问我应该如何解决这个问题呢？

**Comment by spencerwooo** [comment]
我不知道 MikTeX 具体的情况，有什么原因一定要用 MikTeX 不用 TeXLive 吗。
