### ISSUE TITLE
如何将图片的 caption 居中显示？

### ISSUE THREAD

**Issue by sysy12318** [spencerwooo/BIThesis#52]
![E8NSDRAN_ )O1C25~{KE}}L](https://user-images.githubusercontent.com/66873999/84569684-1e79a680-adbb-11ea-9925-2e185685f2b9.png)
过长的图注会出现如图所示无法居中的情况
如果想让图注变成以下格式需要如何操作呢？
![微信图片_20200613211805](https://user-images.githubusercontent.com/66873999/84569766-757f7b80-adbb-11ea-9f08-73129a794293.png)

**Comment by spencerwooo** [comment]
在开头把引入 caption 包那里改为 `\usepackage[center]{caption}` 试一下

**Comment by sysy12318** [comment]
> 
> 
> 在开头把引入 caption 包那里改为 `\usepackage[center]{caption}` 试一下

似乎不起作用，有没有可能是我操作的问题？
![QQ图片20200613231420](https://user-images.githubusercontent.com/66873999/84572302-a9fb3380-adcb-11ea-886e-873a1c08f71b.png)

**Comment by spencerwooo** [comment]
`\usepackage[justification=centering]{caption}` 试一下？
