### ISSUE TITLE
用texstudio的字体报错（作者辛苦！！）

### ISSUE THREAD

**Issue by mwl0811** [spencerwooo/BIThesis#6]
前面所有的安装都是按照git中的要求进行的。
系统：win10
版本：texlive2019, TeXstudio2.12.14-win
报错情况：
![error](https://user-images.githubusercontent.com/40333083/75870348-d2c37280-5e45-11ea-929c-b3c3df8ee9e3.png)
另外，已经确认了系统中有STXihei这个字体，如下：
![image](https://user-images.githubusercontent.com/40333083/75870460-f5558b80-5e45-11ea-8aee-85cd35cd26c7.png)
作者辛苦~~~

**Comment by spencerwooo** [comment]
请问你 TeXstudio 的默认编译方式是什么？在「选项 » 设置 TeXstudio » 构建 » 默认编译器」处可以看到：

![image](https://user-images.githubusercontent.com/32114380/75871031-e7543a80-5e46-11ea-8fa5-765f5a365d9f.png)

**Comment by mwl0811** [comment]
![image](https://user-images.githubusercontent.com/40333083/75871223-31d5b700-5e47-11ea-9d93-d04565217cff.png)
是这样滴

**Comment by spencerwooo** [comment]
你这样试着排查一下：

1. 把「默认编译器」换成 Latexmk，「默认文献工具」不用变。把「设置 TeXstudio » Latexmk」的编译命令里面的参数 `-pdf` 换成 `-xelatex`，也就是 `latexmk.exe -xelatex -silent -synctex=1 %`

![image](https://user-images.githubusercontent.com/32114380/75871621-d0faae80-5e47-11ea-9d1c-1156abd60b74.png)

这样尝试编译一下，看看有没有改善

2. 重新下载一下最新的 Release 压缩包，再编译一下看有没有问题

**Comment by spencerwooo** [comment]
另外，试一下在 PowerShell 里面执行：

```powershell
fc-list :lang-zh > fclist.txt
```

然后把生成的 `fclist.txt` 文件上传一下我瞄一眼

**Comment by spencerwooo** [comment]
**问题已解决**，如果其他人发现类似问题，可以按照如下方法进行排查。

### 华文细黑未安装

排查华文细黑字体名称 `STXihei` 是否有出现在 `fc-list :lang-zh` 的输出中：

![43233f95fb2c82025df0eb3a315ec96](https://user-images.githubusercontent.com/32114380/75876058-ea075d80-5e4f-11ea-912c-989f22030121.jpg)

如果没有对应字体则需要手动下载安装，并需要保证字体文件名称为 `STXIHEI.TTF`：

<img src="https://user-images.githubusercontent.com/32114380/75876177-1f13b000-5e50-11ea-83f0-dd1595073a3d.png" alt="华文黑体字体文件" width="400px" height="auto"/>

### TeXstudio 字体缓存未刷新

排查直接用命令行编译能否成功，按照如下的命令编译主文件名为 `main.tex` 的 LaTeX 项目：

```powershell
xelatex -no-pdf --interaction=nonstopmode main
biber main
xelatex -no-pdf --interaction=nonstopmode main
xelatex --interaction=nonstopmode main
```

如果编译未出现问题，尝试重启或重新按照 TeXstudio，刷新 TeXstudio 字体缓存，重新进行编译尝试。
